//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videohost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutUser
    {
        public int Id { get; set; }
        public string link_photo { get; set; }
        public string about { get; set; }
    
        public virtual User User { get; set; }
    }
}
