//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videohost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikeDislike
    {
        public int Id { get; set; }
        public int id_user { get; set; }
        public int id_video { get; set; }
        public int assessment { get; set; }
    
        public virtual User User { get; set; }
        public virtual Video Video { get; set; }
    }
}
